version: "3.9"

services:
  api:
    build: ./apps/api
    container_name: multibot-api
    env_file: ./apps/api/.env
    ports:
      - "8080:8080"
    volumes:
      - ./apps/api:/app
      - /var/run/docker.sock:/var/run/docker.sock  # For command execution
    depends_on: []
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build: ./apps/web
    container_name: multibot-web
    env_file: ./apps/web/.env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://api:8080
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: multibot-network
