{
  "openapi": "3.0.3",
  "info": {
    "title": "Slack Web API",
    "description": "One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.",
    "version": "1.7.0",
    "contact": {
      "name": "Slack developer relations",
      "url": "https://api.slack.com/support"
    },
    "x-apisguru-categories": [
      "collaboration",
      "messaging"
    ],
    "x-logo": {
      "url": "http://static.tumblr.com/wvuzcz9/LlKncfhmp/slack_logo_240.png"
    },
    "x-origin": [
      {
        "version": "2.0",
        "format": "swagger",
        "url": "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json"
      }
    ],
    "x-providerName": "slack.com"
  },
  "servers": [
    {
      "url": "https://slack.com/api"
    }
  ],
  "paths": {
    "/api.test": {
      "get": {
        "description": "Checks API calling code.",
        "operationId": "api_test",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "api"
        ]
      }
    },
    "/apps.permissions.info": {
      "get": {
        "description": "Returns list of permissions this app has on a team.",
        "operationId": "apps_permissions_info",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "apps.permissions",
          "apps"
        ]
      }
    },
    "/apps.permissions.request": {
      "get": {
        "description": "Allows an app to request additional scopes",
        "operationId": "apps_permissions_request",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "apps.permissions",
          "apps"
        ]
      }
    },
    "/apps.permissions.resources.list": {
      "get": {
        "description": "Returns list of resource grants this app has on a team.",
        "operationId": "apps_permissions_resources_list",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "apps.permissions.resources",
          "apps"
        ]
      }
    },
    "/apps.permissions.scopes.list": {
      "get": {
        "description": "Returns list of scopes this app has on a team.",
        "operationId": "apps_permissions_scopes_list",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "apps.permissions.scopes",
          "apps"
        ]
      }
    },
    "/apps.permissions.users.list": {
      "get": {
        "description": "Returns list of user grants and corresponding scopes this app has on a team.",
        "operationId": "apps_permissions_users_list",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "apps.permissions.users",
          "apps"
        ]
      }
    },
    "/apps.permissions.users.request": {
      "get": {
        "description": "Enables an app to trigger a permissions modal to grant an app access to a user access scope.",
        "operationId": "apps_permissions_users_request",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "apps.permissions.users",
          "apps"
        ]
      }
    },
    "/apps.uninstall": {
      "get": {
        "description": "Uninstalls your app from a workspace.",
        "operationId": "apps_uninstall",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "apps"
        ]
      }
    },
    "/auth.revoke": {
      "get": {
        "description": "Revokes a token.",
        "operationId": "auth_revoke",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "auth"
        ]
      }
    },
    "/auth.test": {
      "get": {
        "description": "Checks authentication & identity.",
        "operationId": "auth_test",
        "security": [
          {
            "slackAuth": [
              "none"
            ]
          }
        ],
        "tags": [
          "auth"
        ]
      }
    },
    "/bots.info": {
      "get": {
        "description": "Gets information about a bot user.",
        "operationId": "bots_info",
        "security": [
          {
            "slackAuth": [
              "users:read"
            ]
          }
        ],
        "tags": [
          "bots"
        ]
      }
    }
    // ... (All other methods would be listed here in similar detail)
  },
  "components": {
    "securitySchemes": {
      "slackAuth": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://slack.com/oauth/authorize",
            "tokenUrl": "https://slack.com/api/oauth.access",
            "scopes": {
              "admin": "admin",
              "admin.apps:read": "admin.apps:read",
              "admin.apps:write": "admin.apps:write",
              "admin.conversations:read": "admin.conversations:read",
              "admin.conversations:write": "admin.conversations:write",
              "admin.invites:read": "admin.invites:read",
              "admin.invites:write": "admin.invites:write",
              "admin.teams:read": "admin.teams:read",
              "admin.teams:write": "admin.teams:write",
              "admin.usergroups:read": "admin.usergroups:read",
              "admin.usergroups:write": "admin.usergroups:write",
              "admin.users:read": "admin.users:read",
              "admin.users:write": "admin.users:write",
              "authorizations:read": "authorizations:read",
              "bot": "Bot user scope",
              "calls:read": "calls:read",
              "calls:write": "calls:write",
              "channels:history": "channels:history",
              "channels:manage": "channels:manage",
              "channels:read": "channels:read",
              "channels:write": "channels:write",
              "chat:write": "chat:write",
              "chat:write:bot": "Author messages as a bot",
              "chat:write:user": "Author messages as a user",
              "conversations:history": "conversations:history",
              "conversations:read": "conversations:read",
              "conversations:write": "conversations:write",
              "dnd:read": "dnd:read",
              "dnd:write": "dnd:write",
              "emoji:read": "emoji:read",
              "files:read": "files:read",
              "files:write:user": "files:write:user",
              "groups:history": "groups:history",
              "groups:read": "groups:read",
              "groups:write": "groups:write",
              "identity.basic": "identity.basic",
              "im:history": "im:history",
              "im:read": "im:read",
              "im:write": "im:write",
              "links:write": "links:write",
              "mpim:history": "mpim:history",
              "mpim:read": "mpim:read",
              "mpim:write": "mpim:write",
              "none": "No scope required",
              "pins:read": "pins:read",
              "pins:write": "pins:write",
              "reactions:read": "reactions:read",
              "reactions:write": "reactions:write",
              "reminders:read": "reminders:read",
              "reminders:write": "reminders:write",
              "remote_files:read": "remote_files:read",
              "remote_files:share": "remote_files:share",
              "remote_files:write": "remote_files:write",
              "rtm:stream": "rtm:stream",
              "search:read": "search:read",
              "stars:read": "stars:read",
              "stars:write": "stars:write",
              "team:read": "team:read",
              "tokens.basic": "tokens.basic",
              "usergroups:read": "usergroups:read",
              "usergroups:write": "usergroups:write",
              "users.profile:read": "users.profile:read",
              "users.profile:write": "users.profile:write",
              "users:read": "users:read",
              "users:read.email": "users:read.email",
              "users:write": "users:write",
              "workflow.steps:execute": "workflow.steps:execute"
            }
          }
        },
        "description": "Learn more about the Slack Web API"
      }
    }
  }
}
